myvote/config/routes.rb
Rails.application.routes.draw do
  resources :addresses

  resources :voters

  resources :vote_records

  resources :elections

  resources :offices

  resources :candidates

end

myvote/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:line_one, :string, :line_two, :line_three)
    end
end

myvote/app/helpers/addresses_helper.rb
module AddressesHelper
end

myvote/app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :line_one %><br>
    <%= f.text_field :line_one %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :line_two %><br>
    <%= f.text_field :line_two %>
  </div>
  <div class="field">
    <%= f.label :line_three %><br>
    <%= f.text_field :line_three %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

myvote/app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

myvote/app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Line one</th>
      <th>String</th>
      <th>Line two</th>
      <th>Line three</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.line_one %></td>
        <td><%= address.string %></td>
        <td><%= address.line_two %></td>
        <td><%= address.line_three %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

myvote/app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

myvote/app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Line one:</strong>
  <%= @address.line_one %>
</p>

<p>
  <strong>String:</strong>
  <%= @address.string %>
</p>

<p>
  <strong>Line two:</strong>
  <%= @address.line_two %>
</p>

<p>
  <strong>Line three:</strong>
  <%= @address.line_three %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>