myvote/config/routes.rb
Rails.application.routes.draw do
  resources :addresses

  resources :voters

  resources :vote_records

  resources :elections

  resources :offices

  resources :candidates

end

myvote/app/models/election.rb
class Election < ActiveRecord::Base
end

myvote/app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  before_action :set_election, only: [:show, :edit, :update, :destroy]

  # GET /elections
  # GET /elections.json
  def index
    @elections = Election.all
  end

  # GET /elections/1
  # GET /elections/1.json
  def show
  end

  # GET /elections/new
  def new
    @election = Election.new
  end

  # GET /elections/1/edit
  def edit
  end

  # POST /elections
  # POST /elections.json
  def create
    @election = Election.new(election_params)

    respond_to do |format|
      if @election.save
        format.html { redirect_to @election, notice: 'Election was successfully created.' }
        format.json { render :show, status: :created, location: @election }
      else
        format.html { render :new }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elections/1
  # PATCH/PUT /elections/1.json
  def update
    respond_to do |format|
      if @election.update(election_params)
        format.html { redirect_to @election, notice: 'Election was successfully updated.' }
        format.json { render :show, status: :ok, location: @election }
      else
        format.html { render :edit }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elections/1
  # DELETE /elections/1.json
  def destroy
    @election.destroy
    respond_to do |format|
      format.html { redirect_to elections_url, notice: 'Election was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_election
      @election = Election.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def election_params
      params.require(:election).permit(:string, :date)
    end
end

myvote/app/helpers/elections_helper.rb
module ElectionsHelper
end

myvote/app/views/elections/_form.html.erb
<%= form_for(@election) do |f| %>
  <% if @election.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@election.errors.count, "error") %> prohibited this election from being saved:</h2>

      <ul>
      <% @election.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

myvote/app/views/elections/edit.html.erb
<h1>Editing Election</h1>

<%= render 'form' %>

<%= link_to 'Show', @election %> |
<%= link_to 'Back', elections_path %>

myvote/app/views/elections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Elections</h1>

<table>
  <thead>
    <tr>
      <th>String</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elections.each do |election| %>
      <tr>
        <td><%= election.string %></td>
        <td><%= election.date %></td>
        <td><%= link_to 'Show', election %></td>
        <td><%= link_to 'Edit', edit_election_path(election) %></td>
        <td><%= link_to 'Destroy', election, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Election', new_election_path %>

myvote/app/views/elections/new.html.erb
<h1>New Election</h1>

<%= render 'form' %>

<%= link_to 'Back', elections_path %>

myvote/app/views/elections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>String:</strong>
  <%= @election.string %>
</p>

<p>
  <strong>Date:</strong>
  <%= @election.date %>
</p>

<%= link_to 'Edit', edit_election_path(@election) %> |
<%= link_to 'Back', elections_path %>